/*4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/

import java.util.Scanner;
public class Q4 {
    public static void main(String[] args){
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter s String: ");
        String s = sc.nextLine();
        System.out.print("Enter t String: ");
        String t = sc.nextLine();
        for(int i=0;i<t.length();i++){
            boolean flag = false;
           for(int j=0;j<s.length();j++){
            if(t.charAt(i)==s.charAt(j)){
                flag = true;
                break;
            }
           }
           if(!flag){
            System.out.print(t.charAt(i));
            break;
           }
        }
    }
}
